language: c
dist: trusty
sudo: yes
env:
  global:
    - secure: "vyyh54RJ4C3ht4RZkrWIe3qxecOh+dsZLw75NHBz5OY/3blfL+YBz5/ZPzKgC1lYOz2lhhrbnr0BptL9kIjdXF1riT43DWRBeGIR9ePR/EaSC/A5jx/FExYI72XSNfl6lpaxbNeKGp7j553WSIdiVmKdpRm4vyexbEz+ZKS/7uznu6+4Tv8PFW4kdcn80cLsl61flLC8eMs3Vy70UXZu6oH+4z7n1quN5Apd0gbcvXWRbEHb9laUNUQNbQw1yIpCfYnzyVaBzesynJbwxSMzMn8QEWfBwTlYIBXi3hw4Ax0eZTJ3EF2ew72R7CM3mw5OnkAsmEqakWrOxk9iKUIhhdbH4AO/b8SQw6W8gJ5Mce5Lf8vx7TR+0NzGp4WtLtAXMYMvMWe0JDVcmyB5YQIs12+a0K0O5nXEDFG+/xcV1REpJBOlpiNHixTSe0cRAd8CMEr9YfCJXZlgmJm81QMJf4Tq/6y3ANMLSNBBtFRdZVi6j1y0Mo8fCsrgBSJ9Ul24NLOY++VfPxeWPupsv9efj89IUOIOr5ZSX1s8Xge+4DNgBJkwFvYUb+1v4qlJzV1R4Px2xaUn7DjYpde7bAUsv/Cydqx8b5ky5Zd94yd9BcpWBFkO5N2Acy5S4r//2z3ZVkQvEzoiG3P8DRjTYbqRst6hDc92I9hcI1++wEl9QWc="

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

      addons:
        apt:
          packages:
            - gcc-aarch64-linux-gnu
            - g++-aarch64-linux-gnu
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
            # - gcc-mips-linux-gnu
            # - g++-mips-linux-gnu
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
            - qemu-user-static
            - qemu-system-arm
            # - qemu-system-mips
            - qemu-system-ppc
        coverity_scan:
          project:
            name: "Naruto/simon_speck"
            description: "<Your project description here>"
          notification_email: tnaruto@gmail.com
          build_command_prepend: "rm -rf build && mkdir -p build && cd build && cmake -DENABLE_TESTING=ON .."
          build_command: "make -j4"
          branch_pattern: develop

install: 
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}
  - pushd ${DEPS_DIR}
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/CMake.app/Contents/bin:${PATH}
    fi
  - cmake --version
  - popd

script:
  - set -e
  - |
    if [[ "${COVERITY_SCAN_BRANCH}" != 1 ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/speck/build_linux.sh
      ./scripts/speck/build_linux_arm.sh
      ./scripts/speck/build_linux_aarch64.sh
      # ./scripts/speck/build_linux_mips.sh
      ./scripts/speck/build_linux_powerpc.sh
    fi
  - |
    if [[ "${COVERITY_SCAN_BRANCH}" != 1 ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./scripts/speck/build_mac.sh
      ./scripts/speck/build_ios.sh
    fi

